name: Daily GitHub Random Repo

on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:

jobs:
  cronrun:
    runs-on: ubuntu-latest
    steps:
      - name: Make script executable
        run: chmod +x ./run.sh
      - name: Run script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git clone https://github.com/${{ github.repository }} repo
          cd repo
          ./run.sh
