name: Daily GitHub Random Repo

on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:

jobs:
  cronrun:
    runs-on: ubuntu-latest
    steps:
      - name: Run script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          SUBSCRIBERS: ${{ secrets.SUBSCRIBERS }}
        run: |
          git clone https://github.com/${{ github.repository }} repo
          cd repo
          chmod +x ./run.sh
          ./run.sh
